encoder: resnet18
attention: homo
#coam_layer_data: [3, [512, 256, 128], [128, 64, 32]]
#,[ 4, 8, 16, 32, 64 ]
coam_layer_data: [ 5, 2, 1, 2, [ 512, 256, 128, 64, 64 ], [ 128, 64, 32, 16, 8 ], [ 4, 8, 16, 32, 64 ] ]
lr: 0.0001
weight_decay: 0.0005
batch_size: 16
test_batch_size: 16
num_dataloader_workers: 8
datasets:
  train_dataset:
    name: coco_train
    class: InpatinedCocoDataset
    args:
      path_to_dataset: /home/ygk/disk/data/coco-inpainted/train
      split: "train"
      method: "centernet"
      image_transformation: "affine"
  val_dataset:
    name: coco_val
    class: InpatinedCocoDataset
    args:
      path_to_dataset: /home/ygk/disk/data/coco-inpainted/train
      split: "val"
      method: "centernet"
      image_transformation: "affine"
  test_datasets:
    - name: coco_test_small
      class: InpatinedCocoDataset
      args:
        path_to_dataset: /home/ygk/disk/data/coco-inpainted/test/small
        split: "test"
        method: "centernet"
        image_transformation: "affine"
    - name: coco_test_medium
      class: InpatinedCocoDataset
      args:
        path_to_dataset: /home/ygk/disk/data/coco-inpainted/test/medium
        split: "test"
        method: "centernet"
        image_transformation: "affine"
    - name: coco_test_large
      class: InpatinedCocoDataset
      args:
        path_to_dataset: /home/ygk/disk/data/coco-inpainted/test/large
        split: "test"
        method: "centernet"
        image_transformation: "affine"
    - name: coco_test_all
      class: ConcatDataset
      datasets:
        - name: coco_test_small
          class: InpatinedCocoDataset
          args:
            path_to_dataset: /home/ygk/disk/data/coco-inpainted/test/small
            split: "test"
            method: "centernet"
            image_transformation: "affine"
        - name: coco_test_medium
          class: InpatinedCocoDataset
          args:
            path_to_dataset: /home/ygk/disk/data/coco-inpainted/test/medium
            split: "test"
            method: "centernet"
            image_transformation: "affine"
        - name: coco_test_large
          class: InpatinedCocoDataset
          args:
            path_to_dataset: /home/ygk/disk/data/coco-inpainted/test/large
            split: "test"
            method: "centernet"
            image_transformation: "affine"