encoder: resnet50
attention: homo
#coam_layer_data: [3, [2048, 1024, 512], [256, 128, 64]]
coam_layer_data: [ 3, 4, 3, 1, [ 2048, 1024, 512], [ 256, 128, 64], [ 4, 8, 16, 32, 64 ] ]
lr: 0.0001
weight_decay: 0.0005
batch_size: 16
test_batch_size: 1
num_dataloader_workers: 8
datasets:
  train_dataset:
    name: coco_train
    class: InpatinedCocoDataset
    args:
      path_to_dataset: /home/ygk/disk/datas/data/coco-inpainted/train
      split: "train"
      method: "centernet"
      image_transformation: "affine"
  val_dataset:
    name: coco_val
    class: InpatinedCocoDataset
    args:
      path_to_dataset: /home/ygk/disk/datas/data/coco-inpainted/train
      split: "val"
      method: "centernet"
      image_transformation: "affine"
  test_datasets:
    - name: kubric
      class: KubricChange
      args:
        path_to_dataset: /home/ygk/disk/datas/data/kubric-change
        split: "test"
        method: "centernet"
